version: "3.9"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  payments-manager:
    build: ./charge-manager
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payments_db
      SPRING_DATASOURCE_USERNAME: payments
      SPRING_DATASOURCE_PASSWORD: payments
      PROXY_URL: http://payments-proxy:8081
      WEBHOOK_TOKEN: ${WEBHOOK_TOKEN}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    depends_on:
      - postgres

  payments-proxy:
    build: ./charge-proxy
    ports:
      - "8081:8081"
    environment:
      MANAGER_URL: http://payments-manager:8080
      ASAAS_API_KEY: ${ASAAS_API_KEY}
      ASAAS_WEBHOOK_TOKEN: ${ASAAS_WEBHOOK_TOKEN}
    depends_on:
      - payments-manager

volumes:
  dbdata:
