version: "3.9"

services:
  payments-manager:
    image: payments/manager:1.5
    ports:
      - "8080:8080"
      - "9091:9091" # SOAP (JAX-WS) do Manager
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/payments_db
      SPRING_DATASOURCE_USERNAME: payments
      SPRING_DATASOURCE_PASSWORD: payments
      PROXY_URL: http://payments-proxy:8081
      PROXY_SOAP_ENABLED: "true"
      PROXY_SOAP_BASE_URL: http://payments-proxy:9090/soap
      # SOAP publicado pelo Manager (porta separada do Tomcat)
      MANAGER_SOAP_BIND_HOST: 0.0.0.0
      MANAGER_SOAP_PORT: 9091
      WEBHOOK_TOKEN: e8f9a1c4-asaas-webhook-secret
      # Optional SMTP (if empty, manager logs "EMAIL-MOCK" to console)
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    depends_on:
      - postgres
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

  payments-proxy:
    image: payments/proxy:1.5
    ports:
      - "8081:8081"
      - "9090:9090"
    environment:
      SPRING_CONFIG_IMPORT: "optional:configtree:/run/secrets/"
      MANAGER_URL: http://payments-manager:8080
      # WSDL do Manager para notificação de pagamento confirmado via SOAP
      MANAGER_SOAP_WSDL_URL: http://payments-manager:9091/soap/PaymentNotificationService?wsdl
      #ASAAS_API_KEY:  ${ASAAS_API_KEY}
      #ASAAS_WEBHOOK_TOKEN:  ${ASAAS_API_KEY}
    secrets:
      - source: asaas_api_key
        target: asaas.api.key
      - source: asaas_webhook_token
        target: asaas.webhook.token
    depends_on:
      - payments-manager
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: payments
      POSTGRES_PASSWORD: payments
      POSTGRES_DB: payments_db
    volumes:
      - dbdata:/var/lib/postgresql/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

volumes:
  dbdata:

networks:
  app-network:
    driver: overlay

secrets:
  asaas_api_key:
    external: true
  asaas_webhook_token:
    external: true